services:
  dca-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10040:3000"
    restart: always
    environment:
      - NODE_ENV=production
    # 메모리 제한 설정 (t2.micro에 적합)
    mem_limit: 900m
    mem_reservation: 512m